name: whisperx
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pytorch==2.1.0
  - torchaudio==2.1.0
  - pytorch-cuda=11.8
  - pip:
    - git+https://github.com/soloHeroo/whisperXdocker.git
    - flask
    - Flask-RESTful
    - Werkzeug
    - gunicorn
